### ISSUE TITLE
Live snippets should not be loaded in config hook

### ISSUE THREAD

**Issue by dontub** [systopia/de.systopia.civioffice#59]
Currently the live snippets are loaded in the [config hook](https://github.com/systopia/de.systopia.civioffice/blob/6f4bb1d80a834957fe5d34e69ca28ca85ef315a1/civioffice.php#L115), so they're loaded on every request, even when not used. Probably the easiest solution would be to register `\CRM_Civioffice_Tokens` as lazy service tagged with `kernel.event_subscriber`.

On one system the early loading of live snippets resulted in a class not found exception:

```
Error: Class "CRM_Sepa_DAO_SEPACreditor" not found in Civi\Api4\Generic\AbstractEntity::getEntityTitle() (line 92 of [...]/drupal/vendor/civicrm/civicrm-core/Civi/Api4/Generic/AbstractEntity.php).

#0 [...]/drupal/vendor/civicrm/civicrm-core/Civi/Api4/Generic/AbstractEntity.php(137): Civi\Api4\Generic\AbstractEntity::getEntityTitle()
#1 [...]/drupal/vendor/civicrm/civicrm-core/Civi/Api4/Provider/ActionObjectProvider.php(158): Civi\Api4\Generic\AbstractEntity::getInfo()
#2 [...]/drupal/vendor/civicrm/civicrm-core/Civi/Api4/Utils/CoreUtil.php(91): Civi\Api4\Provider\ActionObjectProvider->getEntities()
#3 [...]/drupal/vendor/civicrm/civicrm-core/CRM/Core/BAO/CustomGroup.php(2561): Civi\Api4\Utils\CoreUtil::getInfoItem()
#4 [...]/drupal/vendor/civicrm/civicrm-core/CRM/Core/SelectValues.php(238): CRM_Core_BAO_CustomGroup::getCustomGroupExtendsOptions()
#5 [...]/drupal/vendor/civicrm/civicrm-core/CRM/Core/BAO/CustomField.php(380): CRM_Core_SelectValues::customGroupExtends()
#6 [...]/drupal/vendor/civicrm/civicrm-core/api/v3/utils.php(1982): CRM_Core_BAO_CustomField::getFields()
#7 [...]/drupal/vendor/civicrm/civicrm-core/api/v3/utils.php(1954): _civicrm_api_get_custom_fields()
#8 [...]/drupal/vendor/civicrm/civicrm-core/api/v3/Generic.php(91): _civicrm_api_get_fields()
#9 [...]/drupal/vendor/civicrm/civicrm-core/Civi/API/Provider/MagicFunctionProvider.php(85): civicrm_api3_generic_getfields()
#10 [...]/drupal/vendor/civicrm/civicrm-core/Civi/API/Kernel.php(156): Civi\API\Provider\MagicFunctionProvider->invoke()
#11 [...]/drupal/vendor/civicrm/civicrm-core/Civi/API/Kernel.php(79): Civi\API\Kernel->runRequest()
#12 [...]/drupal/vendor/civicrm/civicrm-core/api/api.php(136): Civi\API\Kernel->runSafe()
#13 [...]/drupal/vendor/civicrm/civicrm-core/api/api.php(172): civicrm_api3()
#14 [...]/drupal/vendor/civicrm/civicrm-core/Civi/API/Subscriber/APIv3SchemaAdapter.php(47): _civicrm_api3_api_getfields()
#15 [...]/drupal/vendor/symfony/event-dispatcher/EventDispatcher.php(220): Civi\API\Subscriber\APIv3SchemaAdapter->onApiPrepare()
#16 [...]/drupal/vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
#17 [...]/drupal/vendor/civicrm/civicrm-core/Civi/Core/CiviEventDispatcher.php(263): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#18 [...]/drupal/vendor/civicrm/civicrm-core/Civi/API/Kernel.php(247): Civi\Core\CiviEventDispatcher->dispatch()
#19 [...]/drupal/vendor/civicrm/civicrm-core/Civi/API/Kernel.php(155): Civi\API\Kernel->prepare()
#20 [...]/drupal/vendor/civicrm/civicrm-core/Civi/API/Kernel.php(79): Civi\API\Kernel->runRequest()
#21 [...]/drupal/vendor/civicrm/civicrm-core/api/api.php(136): Civi\API\Kernel->runSafe()
#22 [...]/drupal/web/sites/default/files/civicrm/ext/de.systopia.civioffice/CRM/Civioffice/LiveSnippets.php(34): civicrm_api3()
#23 [...]/drupal/web/sites/default/files/civicrm/ext/de.systopia.civioffice/CRM/Civioffice/LiveSnippets.php(96): CRM_Civioffice_LiveSnippets::get()
#24 [...]/drupal/web/sites/default/files/civicrm/ext/de.systopia.civioffice/CRM/Civioffice/Tokens.php(30): CRM_Civioffice_LiveSnippets::getTokens()
#25 [...]/drupal/web/sites/default/files/civicrm/ext/de.systopia.civioffice/CRM/Civioffice/Tokens.php(25): CRM_Civioffice_Tokens::getTokens()
#26 [...]/drupal/web/sites/default/files/civicrm/ext/de.systopia.civioffice/civioffice.php(115): CRM_Civioffice_Tokens->__construct()
#27 [...]/drupal/vendor/civicrm/civicrm-core/CRM/Utils/Hook.php(276): civioffice_civicrm_config()
#28 [...]/drupal/vendor/civicrm/civicrm-core/CRM/Utils/Hook/DrupalBase.php(73): CRM_Utils_Hook->runHooks()
#29 [...]/drupal/vendor/civicrm/civicrm-core/Civi/Core/CiviEventDispatcher.php(314): CRM_Utils_Hook_DrupalBase->invokeViaUF()
#30 [...]/drupal/vendor/symfony/event-dispatcher/EventDispatcher.php(220): Civi\Core\CiviEventDispatcher::delegateToUF()
#31 [...]/drupal/vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
#32 [...]/drupal/vendor/civicrm/civicrm-core/Civi/Core/CiviEventDispatcher.php(263): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#33 [...]/drupal/vendor/civicrm/civicrm-core/CRM/Utils/Hook.php(168): Civi\Core\CiviEventDispatcher->dispatch()
#34 [...]/drupal/vendor/civicrm/civicrm-core/CRM/Utils/Hook.php(1494): CRM_Utils_Hook->invoke()
#35 [...]/drupal/vendor/civicrm/civicrm-core/CRM/Core/Config.php(96): CRM_Utils_Hook::config()
#36 [...]/drupal/web/modules/contrib/civicrm/src/Civicrm.php(61): CRM_Core_Config::singleton()
#37 [...]/drupal/web/modules/contrib/civicrm/civicrm.user.inc(15): Drupal\civicrm\Civicrm->initialize()
#38 [internal function]: civicrm_user_login()
```

(CiviCRM 5.69.2, org.project60.sepa 1.9.1)

Though the searched class actually exists. Seems to be related how Civi loads extensions... In any case commenting the mentioned line, clearing the Civi cache, and commenting the line in again, solved it on that system.

**Comment by jensschuppe** [comment]
Shouldn't the subscriber class only be instantiated for events it is subscribing to? I thought that's why `\Symfony\Component\EventDispatcher\EventSubscriberInterface::getSubscribedEvents()` is a static method …?

**Comment by dontub** [comment]
The subscriber classes are initialized when the event dispatcher is initialized. The static method could be used, to initialize the subscribers only if a event they subscribed to is dispatched, though it is only used to compile the service container.

**Comment by dontub** [comment]
Note the class not found exception happened once again.
